#!/bin/sh

if [ ! -x /opt/bin/rio ]; then
  exit
fi

case "$1" in
  start)
    # Make /var/lib/rancher persistent
    MOUNT_POINT="/mnt/data"
    mkdir -p /var/lib/rancher
    if [ ! -L /var/lib/rancher ]; then
      if [ ! -d "${MOUNT_POINT}/var/lib/rancher" ]; then
        mkdir -p "${MOUNT_POINT}/var/lib"
        mv /var/lib/rancher "${MOUNT_POINT}/var/lib/rancher"
      else
        rm -rf /var/lib/rancher
      fi
      ln -s "${MOUNT_POINT}/var/lib/rancher" /var/lib/rancher
    fi

    # Stop Docker to release cgroups
    for i in {1..10}; do
      if /etc/init.d/docker status > /dev/null 2>&1; then
        break
      fi
      usleep 500000
    done
    /etc/init.d/docker stop

    printf "Starting Rio Server: "
    start-stop-daemon -S -q -m -b -p /var/run/rio-server.pid --exec /opt/bin/rio server -- \
      --log /var/log/rio-server.log
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping Rio Server: "
    start-stop-daemon -K -q -p /var/run/rio-server.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart)
    "$0" stop
    sleep 1
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac
