#!/bin/sh

if [ ! -x /opt/bin/rio ]; then
  exit
fi

if [ -f /etc/default/rio-agent ]; then
  source /etc/default/rio-agent
fi

case "$1" in
  start)
    printf "Starting Rio Agent: "
    start-stop-daemon -S -q -m -b -p /var/run/rio-agent.pid --exec /bin/bash -- -c \
      "exec /opt/bin/rio agent --server ${SERVER_URL} --token ${NODE_TOKEN} \
        ${RIO_EXTRA_ARGS} &> /var/log/rio-agent.log"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping Rio Agent: "
    start-stop-daemon -K -q -p /var/run/rio-agent.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart)
    "$0" stop
    sleep 1
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac
